### ISSUE TITLE
Kano DevBox not building.

### ISSUE THREAD

**Issue by alexaverill** [KanoComputing/kano-debber#1]
When attempting to get setup for development in Kano DevBox, kano-toolset fails on build.

make[1]: Entering directory `/home/user/Code/kano-debber/kano-toolset___master'
cd kano-keys-pressed && make
make[2]: Entering directory`/home/user/Code/kano-debber/kano-toolset___master/kano-keys-pressed'
g++ -c kano-keys-pressed.cpp
kano-keys-pressed.cpp: In function ‘int main(int, char*_)’:
kano-keys-pressed.cpp:66:36: error: ‘usleep’ was not declared in this scope
make[2]: *_\* [kano-keys-pressed.o] Error 1
make[2]: Leaving directory `/home/user/Code/kano-debber/kano-toolset___master/kano-keys-pressed'
make[1]: *** [kano-keys-pressed] Error 2
make[1]: Leaving directory`/home/user/Code/kano-debber/kano-toolset___master'
dh_auto_build: make -j1 returned exit code 2
make: **\* [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

debuild: fatal error at line 1357:
dpkg-buildpackage -rfakeroot -D -us -uc -i -b failed

Is Kano DevBox now deprecated?

**Comment by convolu** [comment]
Hello, thanks for trying the DevBox. Unfortunately we haven't been actively testing it lately and it may be broken.

We are aware of this issue and it will be fixed soon, but I can't guarantee that there won't be other issues that prevent you from using.

We are looking into possible solutions to provide a developer environment for Kano OS.

**Comment by shuhanxu** [comment]
I am trying to custom Kano OS. Is this OS up to date? If so, how can I create kano img/iso from this dev environment?

Thanks
